"""add site settings

Revision ID: db88606b4690
Revises: 848bc77856ad
Create Date: 2026-07-23 15:09:41.294690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db88606b4690'
down_revision: Union[str, None] = '848bc77856ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.Text(), nullable=True),
    sa.Column('browser_title', sa.Text(), nullable=True),
    sa.Column('hero_title', sa.Text(), nullable=True),
    sa.Column('hero_subtitle', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_settings')
    # ### end Alembic commands ###
