"""add feed fetch schedule settings

Revision ID: e28688a089ed
Revises: 6f6cada780c1
Create Date: 2026-08-31 19:13:40.601789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28688a089ed'
down_revision: Union[str, None] = '6f6cada780c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fetch_enabled', sa.Boolean(), nullable=False),
    sa.Column('fetch_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_status', sa.String(length=32), nullable=True),
    sa.Column('last_run_detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed_settings')
    # ### end Alembic commands ###
